title: Osa
email: brentyi@berkeley.edu
description: A Jekyll Theme
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: https://brentyi.com # the base hostname & protocol for your site, e.g. http://example.com
highlighter: rouge

collections:
  sections:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      latex: no

# host: brentyi.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
