title: Osa
description: A Jekyll Theme

highlighter: rouge

matomo_url: brentyi.com/piwik
matomo_site_id: 0

collections:
  sections:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      latex: no

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
