title: Osa
description: A Jekyll Theme

highlighter: rouge

collections:
  sections:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      latex: no


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
